### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/www-checkgzip#1]
See https://rt.cpan.org/Ticket/Display.html?id=122816

**Comment by benkasminbullock** [comment]
Thank you for reporting this issue.

Deps added here: 6e63687a4fef69812d4b754ef1fb4cb0c09241cb
Test for deps here: 88f1917a1ae8e777060b8ec801d2fdc2485c3325

Closing issue, please feel free to open it again if you are not satisfied.
